author: Arthur Ariel Sabintsev
author_url: http://www.sabintsev.com
github_url: https://github.com/artsabintsev/siren
copyright: "© [Arthur Ariel Sabintsev](http://www.sabintsev.com)"

theme: apple
output: docs
documentation: docs/*.md
clean: true

module: Siren
framework_root: SirenExample/

sdk: iphonesimulator
xcodebuild_arguments:
  - '-workspace'
  - 'SirenExample/SirenExample.xcworkspace'
  - '-scheme'
  - 'SirenExample'
