language: objective-c
osx_image: xcode9.3

notifications:
  email: false
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.1
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -project Example/Example.xcodeproj -scheme Example -destination 'platform:iOS Simulator, id:338C541A-4FE0-47D6-B0AF-9F6308FE76AD, OS:11.3, name:iPhone X' -configuration Debug build test | xcpretty -c
